routes/web.php
            Route::any('employees/{employee?}/departmentid', 'EmployeesController@getEmployeeDepartmentId')->name('get-departmentid');
            Route::get('employees/{employee?}/qualifications', 'EmployeesController@qualifications')->name('get.qualifications');
            Route::any('employees/{employee?}/edit/employee-history', 'EmployeesController@editEmployeeHistory')->name('employee-history');
            Route::any('employees/{employee?}/update/employee-history', 'EmployeesController@updateEmployeeHistory')->name('employees-history.update');
            
            Route::resource('employees', 'EmployeesController');

            Route::resource('announcements', 'AnnouncementsController');
            Route::fileResource('laws');
            Route::fileResource('policies');
            Route::fileResource('topics');
            Route::fileResource('employees');
            //Route::fileResource('assessments');
            Route::resource('organisationcharts', 'OrganisationChartsController', [ 'only' => ['index']]);
            
            Route::resource('assets', 'AssetsController');
            Route::resource('asset_groups', 'AssetGroupsController');
            Route::resource('asset_suppliers', 'AssetSuppliersController');
            Route::resource('asset_allocations', 'AssetAllocationsController');

            Route::resource('surveys', 'SurveysController' );
            Route::get('surveys/{Id}/results', 'SurveysController@results' );
            
            Route::resource('timelines', 'TimelinesController', [
                'parameters' => ['index' => 'employee'],
                'names' => ['show' => 'timelines.index'],
                'only' => ['show']
            ]);
            Route::employeeInResource('rewards');
            Route::employeeInResource('disciplinary_actions');
            
        #endregion

        #region Configuration parameters routes
            Route::group(['prefix'=>'config'], function(){
                Route::get('employees', 'ConfigDropdownsController@employees')->name('employees');
            });
            Route::resource('disciplinary_decisions', 'DisciplinaryDecisionsController');
            Route::resource('disabilities', 'DisabilitiesController');
            Route::resource('disability_categories', 'DisabilityCategoriesController');
            Route::resource('law_categories', 'LawCategoriesController');
            Route::resource('policy_categories', 'PolicyCategoriesController');
            Route::resource('genders', 'GendersController');
            Route::resource('titles', 'TitlesController');
            Route::resource('marital_statuses', 'MaritalStatusesController');
            Route::resource('skills', 'SkillsController');
            Route::resource('teams', 'TeamsController');
            Route::resource('tax_statuses', 'TaxStatusesController');
            Route::resource('branches', 'BranchesController');
            Route::resource('countries', 'CountriesController');
            Route::resource('departments', 'DepartmentsController');
            Route::resource('divisions', 'DivisionsController');
            Route::resource('document_categories', 'DocumentCategoriesController');
            Route::resource('document_types', 'DocumentTypesController');
            Route::resource('employee_statuses', 'EmployeeStatusesController');
            Route::resource('ethnic_groups', 'EthnicGroupsController');
            Route::resource('immigration_statuses', 'ImmigrationStatusesController');
            Route::resource('job_titles', 'JobTitlesController');
            Route::resource('languages', 'LanguagesController');
            Route::resource('time_periods', 'TimePeriodsController');
            Route::resource('time_groups', 'TimeGroupsController');
            Route::resource('products', 'ProductsController');
            //Route::resource('employee_attachment_types', 'EmployeeAttachmentTypesController');
            Route::resource('assessment_types', 'AssessmentTypesController');
            //Route::resource('learning_material_types', 'LearningMaterialTypesController');
            //Route::resource('training_delivery_methods', 'TrainingDeliveryMethodsController');
            Route::resource('product_categories', 'ProductCategoriesController');
            Route::resource('category_question_types', 'CategoryQuestionTypesController');
            Route::resource('companies', 'CompaniesController');
            Route::resource('report_templates', 'ReportTemplatesController');
            Route::resource('sham_user_profiles', 'ShamUserProfilesController');
            Route::any('sham_user_profiles/{Id}/matrix', 'ShamUserProfilesController@matrix')->name('sham_user_profiles.matrix');
            Route::resource('sham_users', 'ShamUsersController');
            Route::resource('users', 'UsersController');
            Route::get('/general_options', 'GeneralOptionsController@index')->name('general_options.index');
            Route::post('/general_options/store', 'GeneralOptionsController@store')->name('general_options.store');
            Route::resource('asset_conditions', 'AssetConditionsController');
            Route::resource('violations', 'ViolationsController');

            Route::resource('contracts', 'ContractsController');
            Route::resource('interviews', 'InterviewsController');
            Route::resource('offers', 'OffersController');
            Route::resource('qualification-recruitments', 'QualificationRecruitmentsController');
        #endregion

        #region E-Learning
            Route::get('elearning', 'MiscController@elearningHelper');
            Route::resource('courses', 'CoursesController' );
            Route::resource('modules', 'ModulesController' );

            Route::get('topics/embed/{file}', 'TopicsController@embedMedia');
            Route::get('topics/{topic?}/snippets', 'TopicsController@getSnippets');
            Route::resource('topics', 'TopicsController' );

            Route::resource('module_assessments', 'ModuleAssessmentsController' );
            Route::resource('module_assessments/{module_assessment}/responses', 'ModuleAssessmentResponsesController',[
                'only'=>['index', 'update']
            ]);
            Route::get('module_assessments/{response}/responses/{module_assessment}/employee/{employee_id}/editAssessment', 'ModuleAssessmentResponsesController@editAssessment');
            Route::resource('course_training_sessions', 'CourseTrainingSessionsController' );
        #endregion

        #region Absences and leaves
        Route::resource('leaves', 'SSPEmployeeLeavesController' );
        Route::get('/leaves/create/{leave_id}/{leave_desc}/{employee_id}', 'SSPEmployeeLeavesController@create');
        Route::get('/leaves/status/{leave_id}/{status}', 'SSPEmployeeLeavesController@changeStatus');
        Route::get('/leaves/batch/{leave_ids}/{status}', 'SSPEmployeeLeavesController@batchChangeStatus');
        Route::post('/leaves/filter', 'SSPEmployeeLeavesController@filterLeave')->name('leaves.filter');
        #endregion

        #region Quality
            Route::any('assessments/assessment/{assessment}/clone', 'AssessmentsController@clone')->name('assessment.clone');
            Route::get('assessments/assessment/{assessment}/cloneForm', 'AssessmentsController@cloneForm')->name('assessments.clone-assessment-form');
            Route::get('assessments/assessment/{assessment}/preview', 'AssessmentsController@preview')->name('assessments.preview');
            Route::resource('assessments', 'AssessmentsController' );
            Route::any('assessments/duplicates/', 'AssessmentsController@duplicates')->name('assessment.duplicates');
            Route::resource('assessment_categories', 'AssessmentCategoriesController');
            Route::resource('category_questions', 'CategoryQuestionsController');
            Route::fileResource('evaluations', 'EvaluationsController');
            Route::any('instances', 'EvaluationsController@showInstances')->name('evaluations.instances');
            Route::get('evaluations/{id}/EvaluationId/{EvaluationId}/assess', 'EvaluationsController@loadAssessment')->name('evaluations.load_assessment');
            Route::post('evaluations/{id}/EvaluationId/{EvaluationId}/submitassessment', 'EvaluationsController@submitAssessment')->name('evaluations.submit_assessment');
            Route::get('evaluations/{assessor}/score/{evaluationid}/show', 'EvaluationsController@score')->name('evaluations.score');
            Route::get('evaluations/{assessor}/score/{evaluationid}/show-score-modal', 'EvaluationsController@scoreCompletedEvaluation')->name('evaluations.score-completed-evaluation');
            Route::any('evaluations/{Id}/name/{name}/downloadscorepdf', 'EvaluationsController@downloadScorePdf' )->name('evaluations.pdfscores');
            Route::any('evaluations/{Id}/EvaluationId/{EvaluationId}/AssessorId/{AssessorId}/summary', 'EvaluationsController@summary')->name('evaluations.summary');
            Route::get('getaudio', 'EvaluationsController@getaudio');
            Route::get('getaudio1', 'EvaluationsController@getaudio1');
            Route::get('getaudiolist', 'EvaluationsController@getaudiolist');
        #endregion

        #region Imports
            Route::get('import', 'ImportsController@getImport')->name('import');
            Route::post('import_parse', 'ImportsController@parseImport')->name('import_parse');
            Route::post('import_process', 'ImportsController@processImport')->name('import_process');
        #endregion

        #region Recruitment
        Route::resource('recruitment', 'RecruitmentsController');

	    Route::post('recruitment_requests/{recruitment_request}/candidate/{candidate}/interview/{interview}/delete-media', 'RecruitmentRequestsController@deleteInterviewMedia')->name('recruitment_requests.delete-interview-media');

app/EthnicGroup.php
<?php

namespace App;


use App\Traits\UsesPredefinedValues;
use Illuminate\Database\Eloquent\SoftDeletes;

class EthnicGroup extends Model
{
    
    use SoftDeletes, UsesPredefinedValues;



    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
                  'description',
                  'is_system_predefined'
              ];

    public $searchable = ['description'];

    public function employees()
    {
        return $this->hasMany('App\Employee','ethnic_group_id','id');
    }


}

app/Http/Controllers/EthnicGroupsController.php
<?php

namespace App\Http\Controllers;

use App\EthnicGroup;
use App\Support\Helper;
use App\SystemSubModule;
use Illuminate\Http\Request;
use App\Http\Controllers\CustomController;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Route;
use Exception;

class EthnicGroupsController extends CustomController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->contextObj = new EthnicGroup();
        $this->baseViewPath = 'ethnic_groups';
        $this->baseFlash = 'Ethnic Group details ';
    }

    /**
     * Display a listing of the ethnic groups.
     *
     * @return Illuminate\View\View
     */
    public function index()
    {
        $ethnicGroups = $this->contextObj::filtered()->paginate(10);

        $allowedActions = Helper::getAllowedActions(SystemSubModule::CONST_ETHNIC_GROUP);

        return view($this->baseViewPath .'.index', compact('ethnicGroups', 'allowedActions'));
    }

    /**
     * Store a new ethnic group in the storage.
     *
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        try {
            $this->validator($request);

            $input = array_except($request->all(),array('_token'));

            $this->contextObj->addData($input);

            \Session::put('success', $this->baseFlash . 'created Successfully!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not create '. $this->baseFlash . '!');
        }

        return redirect()->route($this->baseViewPath .'.index');
    }

    /**
     * Show the form for editing the specified resource.
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Request $request)
    {
        $data = null;
        $id = Route::current()->parameter('ethnic_group');
        $data = $this->contextObj->findData($id);

        if($request->ajax()) {
            $view = view($this->baseViewPath . '.edit', compact('data'))->renderSections();
            return response()->json([
                'title' => $view['modalTitle'],
                'content' => $view['modalContent'],
                'footer' => $view['modalFooter'],
                'url' => $view['postModalUrl']
            ]);
        }
        return view($this->baseViewPath . '.edit', compact('data'));
    }

    /**
     * Update the specified ethnic group in the storage.
     *
     * @param  int $id
     * @param Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validator($request);

            $input = array_except($request->all(),array('_token','_method'));

            $this->contextObj->updateData($id, $input);

            \Session::put('success', $this->baseFlash . 'updated Successfully!!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not create '. $this->baseFlash . '!');
        }

        return redirect()->route($this->baseViewPath .'.index');       
    }

    /**
     * Remove the specified ethnic group from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy(Request $request)
    {
        try {
            $id = Route::current()->parameter('ethnic_group');
            $this->contextObj->destroyData($id);

            \Session::put('success', $this->baseFlash . 'deleted Successfully!!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not delete '. $this->baseFlash . '!');
        }

        return redirect()->route($this->baseViewPath .'.index');
    }

    /**
     * Validate the given request with the defined rules.
     *
     * @param Request $request
     */
    protected function validator(Request $request)
    {
        $validateFields = [
            'description' => 'required|string|min:1|max:50'
        ];

        $this->validate($request, $validateFields);
    }
}

resources/views/ethnic_groups/create.blade.php
@extends(Request::ajax()?'blank':'portal-index')
@section('title', 'Add Ethnic Group')

@section('content')
    <div class="box box-primary">
        <div class="box-body">
            <form method="POST" action="{{ route('ethnic_groups.store') }}" accept-charset="UTF-8" id="create_ethnic_group_form" name="create_ethnic_group_form" class="form-horizontal">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-12">
                        @include('ethnic_groups.form', [
                            'ethnicGroup' => null,
                        ])
                    </div>
                </div>
                <div class="box-footer">
                    <input class="btn btn-primary pull-right" type="submit" value="Add">
                    <a href="{{ route('ethnic_groups.index') }}" class="btn btn-default pull-right" title="Show all Ethnic Groups">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/ethnic_groups/edit.blade.php
@extends(Request::ajax()?'blank':'portal-index')
@section('title', 'Edit Ethnic Group')

@section('modalTitle', 'Edit Ethnic Group')
@section('modalFooter')
    <a href="#!" class="btn" data-close="Close" data-dismiss="modal">Cancel</a>
    <button class="btn btn-primary" type="submit" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Please wait">Update</button>
@endsection

@section('postModalUrl', route('ethnic_groups.update', $data->id))

@section('modalContent')
    <div class="row">
        <div class="col-sm-12">
            @include ('ethnic_groups.form', [
                'ethnicGroup' => $data,
            ])
        </div>
    </div>
    @if(!Request::ajax())
    <div class="box-footer">
        @yield('modalFooter') 
    </div>
    @endif
@endsection

@section('content')
    <form method="POST" action="{{ route('ethnic_groups.update', $data->id) }}" id="edit_ethnic_group_form" name="edit_ethnic_group_form" accept-charset="UTF-8" >
        {{ csrf_field() }}
        <input name="_method" type="hidden" value="PATCH">
        <div class="box box-primary">
            <div class="box-body">
                    @yield('modalContent') 
            </div>
            <div class="box-footer">
                @yield('modalFooter')
            </div>
        </div>
    </form>
@endsection

resources/views/ethnic_groups/form.blade.php
<div class="row">
    
<div class="form-group col-xs-12 {{ $errors->has('description') ? 'has-error' : '' }}">
    <label for="description">Description</label>
        <input class="form-control" name="description" type="text" id="description" value="{{ old('description', optional($ethnicGroup)->description) }}" minlength="1" maxlength="50" required="true" placeholder="Enter description">
        {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
</div>

</div>

resources/views/ethnic_groups/index.blade.php
@extends('portal-index')
@section('title','Ethnic Groups')
@section('subtitle','Ethnic Group drop-down values for employees')
@section('content')
    <br>
    <ul class="nav nav-tabs">
        <li><a href="{{URL::to('/')}}/branches">Branch</a></li>
        <li><a href="{{URL::to('/')}}/countries">Country</a></li>
        <li><a href="{{URL::to('/')}}/departments">Department</a></li>
        <li><a href="{{URL::to('/')}}/divisions">Division</a></li>
        <li><a href="{{URL::to('/')}}/disciplinary_decisions">Disciplinary Decisions</a></li>
        {{--<li><a href="{{URL::to('/')}}/employee_attachment_types">Employee Attachment Types</a></li>--}}
        <li><a href="{{URL::to('/')}}/employee_statuses">Employee Status</a></li>
        <li class="active"><a href="#">Ethnic Group</a></li>
        <li><a href="{{URL::to('/')}}/genders">Gender</a></li>
        <li><a href="{{URL::to('/')}}/immigration_statuses">Immigration Status</a></li>
        <li><a href="{{URL::to('/')}}/job_titles">Job Title</a></li>
        <li><a href="{{URL::to('/')}}/languages">Language</a></li>
        <li><a href="{{URL::to('/')}}/marital_statuses">Marital Status</a></li>
        <li><a href="{{URL::to('/')}}/products">Products </a></li>
        <li><a href="{{URL::to('/')}}/skills">Skills</a></li>
        <li><a href="{{URL::to('/')}}/tax_statuses">Tax Status</a></li>
        <li><a href="{{URL::to('/')}}/time_groups">Time Group</a></li>
        <li><a href="{{URL::to('/')}}/time_periods">Time Periods</a></li>
        <li><a href="{{URL::to('/')}}/teams">Team</a></li>
        <li><a href="{{URL::to('/')}}/titles">Title</a></li>
        <li><a href="{{URL::to('/')}}/disability_categories">Disability Categories</a></li>
        <li><a href="{{URL::to('/')}}/disabilities">Disability</a></li>
        <li><a href="{{URL::to('/')}}/violations">Violations</a></li>
    </ul>
    <div class="flex-wrapper">
        <div id="table-container">
            @if(count($ethnicGroups) > 0)
            <div id="toolbar" class="shadow-eff1">
                <div class="btn-group">
                    @if($allowedActions->contains('Create'))
                    <button id="item-create" type="button" class="btn btn-sham" data-wenk="Add new" data-wenk-pos="bottom">
                        <i class="glyphicon glyphicon-plus"></i> Add New
                    </button>
                    @endif
                </div>
            </div>
            @endif
            <div class="table-responsive">
            @if(count($ethnicGroups) == 0)
                <h4 class="text-center">Its a bit empty here.
                @if($allowedActions->contains('Create'))
                        You may click <a href="javascript:;" class="text-primary item-create">here</a> to add a new ethnic group
                @endif
                </h4>
            @elseif($allowedActions->contains('List'))
                <table id="new-table" data-toggle="table">
                    <thead>
                        <tr>
                                                        <th data-sortable="true">Description</th>

                            <th data-sortable="false" data-tableexport-display="none">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($ethnicGroups as $ethnicGroup)
                        <tr id="tr{{$ethnicGroup->id}}">
                                                        <td>{{ $ethnicGroup->description }}</td>

                            <td data-html2canvas-ignore="true">
                                <div class="btn-group btn-group-xs" role="group">
                                    @if($allowedActions->contains('Write'))
                                    <a href="#light-modal" data-wenk="Edit" class="b-n b-n-r bg-transparent item-edit" onclick="editForm('{{$ethnicGroup->id}}', event)">
                                        <i class="glyphicon glyphicon-edit text-primary"></i>
                                    </a>
                                    @endif
                                    @if($allowedActions->contains('Delete'))
                                    <button class="b-n b-n-r bg-transparent item-remove" data-wenk="Remove" onclick="deleteForm('{{$ethnicGroup->id}}')">
                                        <i class="glyphicon glyphicon-remove text-danger"></i>
                                    </button>
                                    @endif
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <nav>
                    {!! $ethnicGroups->render() !!}
                </nav>
            @endif
            </div>
            @component('partials.index', ['routeName'=> 'ethnic_groups.destroy'])
            @endcomponent
        </div>
    </div>
@endsection