routes/web.php
            });
            Route::resource('disciplinary_decisions', 'DisciplinaryDecisionsController');
            Route::resource('disabilities', 'DisabilitiesController');
            Route::resource('disability_categories', 'DisabilityCategoriesController');
            Route::resource('law_categories', 'LawCategoriesController');
            Route::resource('policy_categories', 'PolicyCategoriesController');
            Route::resource('genders', 'GendersController');
            Route::resource('titles', 'TitlesController');
            Route::resource('marital_statuses', 'MaritalStatusesController');
            Route::resource('skills', 'SkillsController');
            Route::resource('teams', 'TeamsController');
            Route::resource('tax_statuses', 'TaxStatusesController');
            Route::resource('branches', 'BranchesController');
            Route::resource('countries', 'CountriesController');
            Route::resource('departments', 'DepartmentsController');
            Route::resource('divisions', 'DivisionsController');
            Route::resource('document_categories', 'DocumentCategoriesController');
            Route::resource('document_types', 'DocumentTypesController');
            Route::resource('employee_statuses', 'EmployeeStatusesController');
            Route::resource('ethnic_groups', 'EthnicGroupsController');
            Route::resource('immigration_statuses', 'ImmigrationStatusesController');
            Route::resource('job_titles', 'JobTitlesController');
            Route::resource('languages', 'LanguagesController');
            Route::resource('time_periods', 'TimePeriodsController');
            Route::resource('time_groups', 'TimeGroupsController');
            Route::resource('products', 'ProductsController');
            //Route::resource('employee_attachment_types', 'EmployeeAttachmentTypesController');
            Route::resource('assessment_types', 'AssessmentTypesController');
            //Route::resource('learning_material_types', 'LearningMaterialTypesController');
            //Route::resource('training_delivery_methods', 'TrainingDeliveryMethodsController');
            Route::resource('product_categories', 'ProductCategoriesController');
            Route::resource('category_question_types', 'CategoryQuestionTypesController');
            Route::resource('companies', 'CompaniesController');
            Route::resource('report_templates', 'ReportTemplatesController');
            Route::resource('sham_user_profiles', 'ShamUserProfilesController');
            Route::any('sham_user_profiles/{Id}/matrix', 'ShamUserProfilesController@matrix')->name('sham_user_profiles.matrix');
            Route::resource('sham_users', 'ShamUsersController');
            Route::resource('users', 'UsersController');
            Route::get('/general_options', 'GeneralOptionsController@index')->name('general_options.index');
            Route::post('/general_options/store', 'GeneralOptionsController@store')->name('general_options.store');
            Route::resource('asset_conditions', 'AssetConditionsController');
            Route::resource('violations', 'ViolationsController');

            Route::resource('contracts', 'ContractsController');
            Route::resource('interviews', 'InterviewsController');
            Route::resource('offers', 'OffersController');
            Route::resource('qualification-recruitments', 'QualificationRecruitmentsController');
        #endregion

        #region E-Learning
            Route::get('elearning', 'MiscController@elearningHelper');
            Route::resource('courses', 'CoursesController' );
            Route::resource('modules', 'ModulesController' );

            Route::get('topics/embed/{file}', 'TopicsController@embedMedia');
            Route::get('topics/{topic?}/snippets', 'TopicsController@getSnippets');
            Route::resource('topics', 'TopicsController' );

            Route::resource('module_assessments', 'ModuleAssessmentsController' );
            Route::resource('module_assessments/{module_assessment}/responses', 'ModuleAssessmentResponsesController',[
                'only'=>['index', 'update']
            ]);
            Route::get('module_assessments/{response}/responses/{module_assessment}/employee/{employee_id}/editAssessment', 'ModuleAssessmentResponsesController@editAssessment');
            Route::resource('course_training_sessions', 'CourseTrainingSessionsController' );
        #endregion

        #region Absences and leaves
        Route::resource('leaves', 'SSPEmployeeLeavesController' );
        Route::get('/leaves/create/{leave_id}/{leave_desc}/{employee_id}', 'SSPEmployeeLeavesController@create');
        Route::get('/leaves/status/{leave_id}/{status}', 'SSPEmployeeLeavesController@changeStatus');
        Route::get('/leaves/batch/{leave_ids}/{status}', 'SSPEmployeeLeavesController@batchChangeStatus');
        Route::post('/leaves/filter', 'SSPEmployeeLeavesController@filterLeave')->name('leaves.filter');
        #endregion

        #region Quality
            Route::any('assessments/assessment/{assessment}/clone', 'AssessmentsController@clone')->name('assessment.clone');
            Route::get('assessments/assessment/{assessment}/cloneForm', 'AssessmentsController@cloneForm')->name('assessments.clone-assessment-form');
            Route::get('assessments/assessment/{assessment}/preview', 'AssessmentsController@preview')->name('assessments.preview');
            Route::resource('assessments', 'AssessmentsController' );
            Route::any('assessments/duplicates/', 'AssessmentsController@duplicates')->name('assessment.duplicates');
            Route::resource('assessment_categories', 'AssessmentCategoriesController');
            Route::resource('category_questions', 'CategoryQuestionsController');
            Route::fileResource('evaluations', 'EvaluationsController');
            Route::any('instances', 'EvaluationsController@showInstances')->name('evaluations.instances');
            Route::get('evaluations/{id}/EvaluationId/{EvaluationId}/assess', 'EvaluationsController@loadAssessment')->name('evaluations.load_assessment');
            Route::post('evaluations/{id}/EvaluationId/{EvaluationId}/submitassessment', 'EvaluationsController@submitAssessment')->name('evaluations.submit_assessment');
            Route::get('evaluations/{assessor}/score/{evaluationid}/show', 'EvaluationsController@score')->name('evaluations.score');
            Route::get('evaluations/{assessor}/score/{evaluationid}/show-score-modal', 'EvaluationsController@scoreCompletedEvaluation')->name('evaluations.score-completed-evaluation');
            Route::any('evaluations/{Id}/name/{name}/downloadscorepdf', 'EvaluationsController@downloadScorePdf' )->name('evaluations.pdfscores');
            Route::any('evaluations/{Id}/EvaluationId/{EvaluationId}/AssessorId/{AssessorId}/summary', 'EvaluationsController@summary')->name('evaluations.summary');
            Route::get('getaudio', 'EvaluationsController@getaudio');
            Route::get('getaudio1', 'EvaluationsController@getaudio1');
            Route::get('getaudiolist', 'EvaluationsController@getaudiolist');
        #endregion

        #region Imports
            Route::get('import', 'ImportsController@getImport')->name('import');
            Route::post('import_parse', 'ImportsController@parseImport')->name('import_parse');
            Route::post('import_process', 'ImportsController@processImport')->name('import_process');
        #endregion

        #region Recruitment
        Route::resource('recruitment', 'RecruitmentsController');

	    Route::post('recruitment_requests/{recruitment_request}/candidate/{candidate}/interview/{interview}/delete-media', 'RecruitmentRequestsController@deleteInterviewMedia')->name('recruitment_requests.delete-interview-media');
        Route::get('recruitment_requests/{recruitment_request}/candidate/{candidate}/interview/{interview}/download-media/{media}', 'RecruitmentRequestsController@downloadInterviewMedia')->name('recruitment_requests.download-interview-media');

        Route::get('recruitment_requests/{recruitment_request}/stages/{interview}/candidate/{candidate?}/edit-interview', 'RecruitmentRequestsController@editInterview')->name('recruitment_requests.edit-interview');
        Route::patch('recruitment_requests/{recruitment_request}/stages/{interview}/candidate/{candidate?}/update-interview', 'RecruitmentRequestsController@updateInterview')->name('recruitment_requests.update-interview');
        Route::fileResource('recruitment_requests', 'RecruitmentRequestsController');
        Route::get('recruitment_requests/{recruitment_request}/stages', 'RecruitmentRequestsController@showStages')->name('recruitment_requests.stages');
        Route::get('recruitment_requests/{recruitment_request}/candidates', 'RecruitmentRequestsController@getCandidates')->name('recruitment_requests.candidates-list');
        Route::get('recruitment_requests/{recruitment_request}/offer-letters', 'RecruitmentRequestsController@getOfferLetters')->name('recruitment_requests.offer-letters-list');
        Route::get('recruitment_requests/{recruitment_request}/contracts', 'RecruitmentRequestsController@getContracts')->name('recruitment_requests.contracts-list');
        Route::post('recruitment_requests/{recruitment_request}/switch/{candidate}/{state}', 'RecruitmentRequestsController@stateSwitch')->name('recruitment_requests.update-status');
        Route::post('recruitment_requests/{recruitment_request}/interviewing/{candidate}', 'RecruitmentRequestsController@getInterviewing')->name('recruitment_requests.get-interviewing');
        Route::post('recruitment_requests/{recruitment_request}/upload-offer', 'RecruitmentRequestsController@saveSignedOfferForm')->name('recruitment_requests.upload-offer');

app/Offer.php
<?php

namespace App;

use Plank\Mediable\Mediable;
use Illuminate\Database\Eloquent\SoftDeletes;

class Offer extends Model
{
    use Mediable;
    use SoftDeletes;



    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
                  'description',
                  'content'
              ];



}

app/Http/Controllers/OffersController.php
<?php

namespace App\Http\Controllers;

use App\Offer;
use Illuminate\Http\Request;
use App\Http\Controllers\CustomController;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use Exception;

class OffersController extends CustomController
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->contextObj = new Offer();
        $this->baseViewPath = 'offers';
        $this->baseFlash = 'Offer details ';
    }

    /**
     * Display a listing of the offers.
     *
     * @return Illuminate\View\View
     */
    public function index()
    {
        $offers = $this->contextObj::filtered()->paginate(10);
        return view($this->baseViewPath .'.index', compact('offers'));
    }

    /**
     * Store a new offer in the storage.
     *
     * @param Illuminate\Http\Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function store(Request $request)
    {
        try {
            $this->validator($request);

            $input = array_except($request->all(),array('_token'));

            $this->contextObj->addData($input);

            \Session::put('success', $this->baseFlash . 'created Successfully!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not create '. $this->baseFlash . '!');
        }

        return redirect()->route($this->baseViewPath .'.index');
    }

    public function edit(Request $request)
    {
        $id = Route::current()->parameter('offer');
        $data = $this->contextObj->findData($id);

        if($request->ajax()) {
            $view = view($this->baseViewPath . '.edit', compact('data'))->renderSections();
            return response()->json([
                'title' => $view['modalTitle'],
                'content' => $view['modalContent'],
                'footer' => $view['modalFooter'],
                'url' => $view['postModalUrl']
            ]);
        }

        return view($this->baseViewPath . '.edit', compact('data'));
    }
    /**
     * Update the specified offer in the storage.
     *
     * @param  int $id
     * @param Request $request
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function update(Request $request, $id)
    {
        try {
            $this->validator($request);
            
            $redirectsTo = $request->get('redirectsTo', route($this->baseViewPath .'.index'));
            
            $input = array_except($request->all(),array('_token','_method','redirectsTo'));

            $this->contextObj->updateData($id, $input);

            \Session::put('success', $this->baseFlash . 'updated Successfully!!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not update '. $this->baseFlash . '!');
        }

        return Redirect::to($redirectsTo);
    }

    /**
     * Remove the specified offer from the storage.
     *
     * @param  int $id
     *
     * @return Illuminate\Http\RedirectResponse | Illuminate\Routing\Redirector
     */
    public function destroy(Request $request)
    {
        try {
            $id = Route::current()->parameter('offer');
            $this->contextObj->destroyData($id);

            \Session::put('success', $this->baseFlash . 'deleted Successfully!!');

        } catch (Exception $exception) {
            \Session::put('error', 'could not delete '. $this->baseFlash . '!');
        }

        return redirect()->back();
    }
    
    

    /**
     * Validate the given request with the defined rules.
     *
     * @param Request $request
     */
    protected function validator(Request $request)
    {
        $validateFields = [
            'description' => 'required|string|min:0|max:100'
        ];

        $validator = Validator::make($request->all(), $validateFields);
        if($validator->fails()) {
            return redirect()->back()
                ->withInput($request->all())
                ->withErrors($validator);
        }
    }
}

resources/views/offers/create.blade.php
@extends(Request::ajax()?'blank':'portal-index')
@section('title', 'Add Offer')

@section('content')
    <div class="box box-primary">
        <div class="box-body">
            <form method="POST" action="{{ route('offers.store') }}" accept-charset="UTF-8" id="create_offer_form" name="create_offer_form" class="form-horizontal">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-12">
                        @include('offers.form', [
                            'offer' => null,
                        ])
                    </div>
                </div>
                <div class="box-footer">
                    <input class="btn btn-primary pull-right" type="submit" value="Add">
                    <a href="{{ route('offers.index') }}" class="btn btn-default pull-right" title="Show all Offers">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/offers/edit.blade.php
@extends(Request::ajax()?'blank':'portal-index')
@section('title', 'Edit Offer')

@section('content')
    <form method="POST" action="{{ route('offers.update', $data->id) }}" id="edit_offer_form" name="edit_offer_form" accept-charset="UTF-8" >
        {{ csrf_field() }}
        <input name="_method" type="hidden" value="PATCH">
        <div class="row">
            <div class="col-sm-12">
                @include ('offers.form', [
                    'offer' => $data,
                ])
            </div>
        </div>

        <div class="row">
            <div class="col-sm-12 text-right">
                <a href="{{route('offers.index')}}" class="btn" data-close="Close" data-dismiss="modal">Cancel</a>
                <button class="btn btn-primary" type="submit" id="btnSave" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Please wait">Save</button>
            </div>
        </div>
    </form>
@endsection

resources/views/offers/form.blade.php
<div class="row">
    <div class="form-group col-xs-12 {{ $errors->has('description') ? 'has-error' : '' }}">
        <label for="description">Description</label>
            <input class="form-control" name="description" type="text" id="description" value="{{ old('description', optional($offer)->description) }}" minlength="1" maxlength="100" required="true" placeholder="Enter description">
            {!! $errors->first('description', '<p class="help-block">:message</p>') !!}
    </div>
</div>

<div class="row">
    <div style="border:1px solid #ccc;overflow:hidden;margin:0 15px 20px 15px;background-color:#fff;padding:20px; 0;">
        <div class="col-xs-12"><i class="fa fa-info-circle" data-wenk="The labels below are placeholder text. Click to insert into the text zone below" data-wenk-pos="right"></i></div>
        <div class="col-xs-1">Recruitment</div>
        <div class="col-xs-11">
            <span class="label label-primary" onclick="insertPlaceHolder('[[recruitment Job Title]]')" style="user-drag: none;cursor:pointer;">Job Title</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[recruitment Department]]')" style="user-drag: none;cursor:pointer;">Department</span>
        </div>
        <div class="col-xs-1">Candidate</div>
        <div class="col-xs-11" style="user-drag: none;">
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Title]]')" style="user-drag: none;cursor:pointer;">Title</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Name]]')" style="user-drag: none;cursor:pointer;">Name</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Phone Number]]')" style="user-drag: none;cursor:pointer;">Phone Number</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Address Line 1]]')" style="user-drag: none;cursor:pointer;">Address Line 1</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Address Line 2]]')" style="user-drag: none;cursor:pointer;">Address Line 2</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Address Line 3]]')" style="user-drag: none;cursor:pointer;">Address Line 3</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Address Line 4]]')" style="user-drag: none;cursor:pointer;">Address Line 4</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate City]]')" style="user-drag: none;cursor:pointer;">City</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Province]]')" style="user-drag: none;cursor:pointer;">Province</span>
            <span class="label label-primary" onclick="insertPlaceHolder('[[candidate Zip code]]')" style="user-drag: none;cursor:pointer;">Zip Code</span>
        </div>
    </div>
</div>

<div class="row">
    <div class="form-group col-xs-12 {{ $errors->has('content') ? 'has-error' : '' }}">
        <label for="content">Content <i class="fa fa-info-circle text-danger" data-wenk="Required"></i></label>
            <textarea class="form-control" name="content" cols="50" rows="5" id="tiny" placeholder="Enter content">{{ old('content', optional($offer)->content) }}</textarea>
            {!! $errors->first('content', '<p class="help-block">:message</p>') !!}
    </div>
</div>

@section('post-body')
    <script src="{{URL::to('/')}}/js/tinymce.min.js"></script>
@endsection

resources/views/offers/index.blade.php
@extends('portal-index')
@section('title','Offers')
@section('subtitle','Offers drop-down values for the Recruitment module')
@section('content')
    <br>
    <ul class="nav nav-tabs">
        <li><a href="{{URL::to('/')}}/contracts">Contracts</a></li>
        <li><a href="{{URL::to('/')}}/interviews">Interviews</a></li>
        <li class="active"><a href="#">Offers</a></li>
        <li><a href="{{URL::to('/')}}/qualification-recruitments">Qualifications</a></li>
    </ul>
    <div class="flex-wrapper">
        <div id="table-container">
            @if(count($offers) > 0)
            <div id="toolbar" class="shadow-eff1">
                <div class="btn-group">
                    <button id="item-create" type="button" class="btn btn-sham" data-wenk="Add new" data-wenk-pos="bottom">
                        <i class="glyphicon glyphicon-plus"></i> Add New
                    </button>
                </div>
            </div>
            @endif
            <div class="table-responsive">
            @if(count($offers) == 0)
                <h4 class="text-center">Its a bit empty here. You may click <a href="javascript:;" class="text-primary item-create">here</a> to add a new offer</h4>
            @else
                <table id="new-table" data-toggle="table">
                    <thead>
                        <tr>
                                                        <th data-sortable="true">Description</th>

                            <th data-sortable="false" data-tableexport-display="none">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($offers as $offer)
                        <tr id="tr{{$offer->id}}">
                                                        <td>{{ $offer->description }}</td>

                            <td data-html2canvas-ignore="true">
                                <div class="btn-group btn-group-xs" role="group">
                                    <button type="button" class="b-n b-n-r bg-transparent item-edit" data-wenk="Edit" onclick="editFullPage('{{$offer->id}}', event)">
                                        <i class="glyphicon glyphicon-edit text-primary"></i>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <nav>
                    {!! $offers->render() !!}
                </nav>
            @endif
            </div>
            @component('partials.index', ['routeName'=> 'offers.destroy'])
            @endcomponent
        </div>
    </div>
@endsection