routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'MiscController@welcome');
Route::get('test', 'MiscController@test');
Route::get('vue-test', 'MiscController@vueTest');
Route::get('testleave', 'MiscController@testleave');
Route::get('testunclaimedmonthly', 'MiscController@testunclaimedmonthly');

Auth::routes();

#region auth middleware routes
    Route::group(['middleware' => ['auth']], function() {

        // logout using get
        Route::get('auth/logout', 'Auth\LoginController@logout')->name('logout');

        #region Dashboard & Reports
            Route::resource('home', 'HomeController', [ 'only' => ['index'] ]);
            Route::resource('dashboard', 'HomeController', [ 'only' => ['index'] ]);
            
            Route::get('getHeadcountData', 'HomeController@getHeadcountData')->name('getHeadcountData');
            Route::get('getHeadcountDeptData', 'HomeController@getHeadcountDeptData')->name('getHeadcountDeptData');
            Route::get('getNewHiresData', 'HomeController@getNewHiresData')->name('getNewHiresData');
            Route::get('getAssetData', 'HomeController@getAssetData')->name('getAssetData');
            Route::get('getCourseData', 'HomeController@getCourseData')->name('getCourseData');
            Route::get('getRewardCount', 'HomeController@getRewardCount')->name('getRewardCount');
            Route::get('getDisciplinaryActionCount', 'HomeController@getDisciplinaryActionCount')->name('getDisciplinaryActionCount');
            Route::get('getQALastFiveDaysData', 'HomeController@getQALastFiveDaysData')->name('getQALastFiveDaysData');
            Route::get('getQAEvaluationScoresData', 'HomeController@getQAEvaluationScoresData')->name('getQAEvaluationScoresData');
            Route::get('getTotalAssessmentData', 'HomeController@getTotalAssessmentData')->name('getTotalAssessmentData');

            Route::resource('reports', 'ReportController' );
        #endregion

        #region MyPortal
            Route::resource('selfservice-portal', 'SSPController');

            Route::get('my-details/getProfile', 'SSPMyDetailsController@getProfile');
            Route::resource('my-details', 'SSPMyDetailsController',[
                'only'=>['index','update']
            ]);

            Route::resource('my-elearning/my-assessments', 'SSPMyCourseAssessmentsController',[
                'only'=>['index']
            ]);
            Route::post('my-elearning/enrol', 'SSPMyCourseController@enrol')->name('courseEnrol');;
            Route::get('my-elearning/my-courses', 'SSPMyCourseController@myCourses');
            Route::get('my-course/{Id}','SSPMyCourseController@renderTopic');
            Route::any('my-courses/{Id}/assessment/{assmId}', 'SSPMyCourseController@manageAssessment');
            Route::any('my-courses/{Id}/assessment/{assmId}/post/{status}', 'SSPMyCourseController@manageAssessment');
            Route::get('topic-attachment/{Id}/download', 'SSPMyCourseController@download')->name('sspmycourses.download');
            Route::get('my-courses/{Id}/getAssessmentData/', 'SSPMyCourseController@getAssessmentData')->name('sspmycourses.getassessmentdata');
            Route::get('my-courses/{Id}/getattachments/', 'SSPMyCourseController@getTopicAttachments');
            Route::get('my-courses/{Id}/restart/', 'SSPMyCourseController@restartCourse');
            Route::get('my-courses/{Id}/getattachments/', 'SSPMyCourseController@getTopicAttachments');
            Route::post('my-courses/progress', 'SSPMyCourseController@updateCourseProgress');
            Route::resource('my-courses', 'SSPMyCourseController',[
                'only'=>['index']
            ]);

            Route::resource('my-surveys', 'SSPMySurveysController');
            Route::any('survey-thumbnail/{formId}', 'SSPMySurveysController@getFormData');
        #endregion

        #region Central HR
            // "duplicate" routes to work with both create and edit mode
            Route::get('employees/check-id', 'EmployeesController@checkId');
            Route::get('employees/{employee}/check-id', 'EmployeesController@checkId');    
            Route::get('employees/check-name', 'EmployeesController@checkEmployee');
            Route::get('employees/{employee}/check-name', 'EmployeesController@checkEmployee');
            Route::get('employees/check-passport', 'EmployeesController@checkPassport');
            Route::get('employees/{employee}/check-passport', 'EmployeesController@checkPassport');
            Route::get('employees/check-employeeno', 'EmployeesController@checkEmployeeNo');
            Route::get('employees/{employee}/check-employeeno', 'EmployeesController@checkEmployeeNo')->name('check-employeeno');

            Route::any('employees/{employee?}/departmentid', 'EmployeesController@getEmployeeDepartmentId')->name('get-departmentid');
            Route::get('employees/{employee?}/qualifications', 'EmployeesController@qualifications')->name('get.qualifications');
            Route::any('employees/{employee?}/edit/employee-history', 'EmployeesController@editEmployeeHistory')->name('employee-history');
            Route::any('employees/{employee?}/update/employee-history', 'EmployeesController@updateEmployeeHistory')->name('employees-history.update');
            
            Route::resource('employees', 'EmployeesController');

            Route::resource('announcements', 'AnnouncementsController');
            Route::fileResource('laws');
            Route::fileResource('policies');
            Route::fileResource('topics');
            Route::fileResource('employees');
            //Route::fileResource('assessments');
            Route::resource('organisationcharts', 'OrganisationChartsController', [ 'only' => ['index']]);
            
            Route::resource('assets', 'AssetsController');
            Route::resource('asset_groups', 'AssetGroupsController');
            Route::resource('asset_suppliers', 'AssetSuppliersController');
            Route::resource('asset_allocations', 'AssetAllocationsController');

            Route::resource('surveys', 'SurveysController' );
            Route::get('surveys/{Id}/results', 'SurveysController@results' );
            
            Route::resource('timelines', 'TimelinesController', [
                'parameters' => ['index' => 'employee'],
                'names' => ['show' => 'timelines.index'],
                'only' => ['show']
            ]);
            Route::employeeInResource('rewards');
            Route::employeeInResource('disciplinary_actions');
            
        #endregion

        #region Configuration parameters routes
            Route::group(['prefix'=>'config'], function(){
                Route::get('employees', 'ConfigDropdownsController@employees')->name('employees');
            });
            Route::resource('disciplinary_decisions', 'DisciplinaryDecisionsController');
            Route::resource('disabilities', 'DisabilitiesController');
            Route::resource('disability_categories', 'DisabilityCategoriesController');
            Route::resource('law_categories', 'LawCategoriesController');
            Route::resource('policy_categories', 'PolicyCategoriesController');
            Route::resource('genders', 'GendersController');
            Route::resource('titles', 'TitlesController');
            Route::resource('marital_statuses', 'MaritalStatusesController');
            Route::resource('skills', 'SkillsController');
            Route::resource('teams', 'TeamsController');
            Route::resource('tax_statuses', 'TaxStatusesController');
            Route::resource('branches', 'BranchesController');
            Route::resource('countries', 'CountriesController');
            Route::resource('departments', 'DepartmentsController');
            Route::resource('divisions', 'DivisionsController');
            Route::resource('document_categories', 'DocumentCategoriesController');
            Route::resource('document_types', 'DocumentTypesController');
            Route::resource('employee_statuses', 'EmployeeStatusesController');
            Route::resource('ethnic_groups', 'EthnicGroupsController');
            Route::resource('immigration_statuses', 'ImmigrationStatusesController');
            Route::resource('job_titles', 'JobTitlesController');
            Route::resource('languages', 'LanguagesController');
            Route::resource('time_periods', 'TimePeriodsController');
            Route::resource('time_groups', 'TimeGroupsController');
            Route::resource('products', 'ProductsController');
            //Route::resource('employee_attachment_types', 'EmployeeAttachmentTypesController');
            Route::resource('assessment_types', 'AssessmentTypesController');
            //Route::resource('learning_material_types', 'LearningMaterialTypesController');
            //Route::resource('training_delivery_methods', 'TrainingDeliveryMethodsController');
            Route::resource('product_categories', 'ProductCategoriesController');
            Route::resource('category_question_types', 'CategoryQuestionTypesController');
            Route::resource('companies', 'CompaniesController');
            Route::resource('report_templates', 'ReportTemplatesController');
            Route::resource('sham_user_profiles', 'ShamUserProfilesController');
            Route::any('sham_user_profiles/{Id}/matrix', 'ShamUserProfilesController@matrix')->name('sham_user_profiles.matrix');
            Route::resource('sham_users', 'ShamUsersController');
            Route::resource('users', 'UsersController');

app/Assessment.php
<?php

namespace App;


use Illuminate\Database\Eloquent\SoftDeletes;

class Assessment extends Model
{
    
    use SoftDeletes;



    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
                  'name',
                  'description',
                  'passmark_percentage'
              ];

    public $searchable = ['name','description'];

    public function assessmentAssessmentCategory()
    {
        return $this->belongsToMany(AssessmentCategory::class,'assessments_assessment_category','assessment_id','assessment_category_id')
            ->withPivot('is_active')->where('assessments_assessment_category.is_active',1);
    }

    public function evaluationResults()
    {
        return $this->hasMany('App\EvaluationResult','assessment_id','id');
    }

    public function evaluations()
    {
        return $this->hasMany('App\Evaluation','assessment_id','id');
    }

    public function evaluationResultsEvaluations()
    {
        return $this->belongsToMany(Evaluation::class,'evaluation_results','assessment_id','evaluation_id');
    }

    public function isAssessmentInUse()
    {
        $retvalue = false;
        $count = count($this->belongsToMany(Evaluation::class,'evaluation_results','assessment_id','evaluation_id')->get());
        if($count > 0)
        {
            $retvalue = true;
        }
        return $retvalue;
    }

}

app/AssessmentType.php
<?php

namespace App;


use App\Traits\UsesPredefinedValues;
use Illuminate\Database\Eloquent\SoftDeletes;

class AssessmentType extends Model
{
    use SoftDeletes, UsesPredefinedValues;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'assessment_types';

    /**
     * The database primary key value.
     *
     * @var string
     */
    protected $primaryKey = 'id';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'description',
        'is_system_predefined'
    ];

    public $searchable = ['description'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];




}

resources/views/assessments/clone.blade.php
@extends('portal-index')
@section('title', 'Clone Assessment')
@section('modalTitle', 'Clone Assessment')
@section('modalFooter')
    <a href="#!" class="btn" data-close="Close" data-dismiss="modal">Cancel</a>
    <button class="btn btn-primary" type="submit" data-loading-text="<i class='fa fa-spinner fa-spin'></i> Please wait">Clone</button>
@endsection

@section('postModalUrl', route('assessment.clone', $assessment->id))

@section('modalContent')
    <div class="row">
        <div class="col-sm-12">
            @include ('assessments.clone_form', [
                'assessment' => $assessment,
                'assessmentCategories' => $assessmentCategories,
            ])
        </div>
    </div>
    @if(!Request::ajax())
    <div class="box-footer">
        @yield('modalFooter')
    </div>
    @endif
@endsection

@section('content')
    <form method="POST" action="{{ route('assessment.clone', $assessment->id) }}" id="clone_assessment_form" name="clone_assessment_form" accept-charset="UTF-8" >
        {{ csrf_field() }}
        <div class="box box-primary">
            <div class="box-body">
                    @yield('modalContent')
            </div>
            <div class="box-footer">
                @yield('modalFooter')
            </div>
        </div>
    </form>
@endsection

resources/views/assessments/clone_form.blade.php
<div class="row">
    <div class="form-group col-xs-6 {{ $errors->has('name') ? 'has-error' : '' }}">
        <label for="name">Assessment Name</label>
            <input class="form-control" type="text" value="{{ old('name', isset($assessment->name) ? $assessment->name : null) }}" readonly="readonly" disabled="disabled">
            {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>

    <div class="form-group col-xs-6 {{ $errors->has('name') ? 'has-error' : '' }} pull-right">
        <label for="name">New Assessment Name</label>
        <input class="form-control" name="assessment" type="text" id="assessment"  minlength="1" maxlength="1024" required="true" placeholder="Enter new assessment name">
        {!! $errors->first('name', '<p class="help-block">:message</p>') !!}
    </div>
</div>
<div class="row">
    @foreach($assessmentCategories as $key=>$assessmentCategory)
        <div class="form-group col-xs-6 {{ $errors->has('assessmentCategory_'.$assessmentCategory->id) ? 'has-error' : '' }}">
            <label for="name">Assessment Category Name</label>
            <input class="form-control" type="text" value="{{ old('name', isset($assessmentCategory->name) ? $assessmentCategory->name : null) }}" readonly="readonly" disabled="disabled">
            {!! $errors->first('assessmentCategory[]', '<p class="help-block">:message</p>') !!}
        </div>
        <div class="form-group col-xs-6 {{ $errors->has('assessmentCategory_'.$assessmentCategory->id) ? 'has-error' : '' }}">
            <label for="name">New Assessment Category Name</label>
            <input class="form-control" name="assessmentCategory[]" type="text" id="assessmentCategory[]"  minlength="1" maxlength="1024" required="true" placeholder="Enter new assessment category name">
            {!! $errors->first('assessmentCategory[]', '<p class="help-block">:message</p>') !!}
        </div>
    @endforeach
</div>

resources/views/assessments/create.blade.php
@extends('portal-index')
@section('title', 'Add Assessment')

@section('content')
    <div class="box box-primary">
        <div class="box-body">
            <form method="POST" action="{{ route('assessments.store') }}" accept-charset="UTF-8" id="assessment_form" name="create_assessment_form" class="form-horizontal">
                {{ csrf_field() }}
                <div class="row">
                    <div class="col-sm-12">
                        @include('assessments.form', [
                            'assessment' => null,
                        ])
                    </div>
                </div>
                <div class="box-footer">
                    <input class="btn btn-primary pull-right" type="submit" value="Add">
                    <a href="{{ route('assessments.index') }}" class="btn btn-default pull-right" title="Show all Assessments">
                        <span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>
                    </a>
                </div>
            </form>
        </div>
    </div>
@endsection
@section('post-body')
    <script src="{{url('/')}}/plugins/multiselect/multiselect.min.js"></script>
    <script>
        $(function () {
            $('.multipleSelect').each(function(){
                $(this).multiselect({
                    submitAllLeft:false,
                    sort: false,
                    keepRenderingSort: false,
                    search: {
                        left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                        right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                    },
                    fireSearch: function(value) {
                        return value.length > 3;
                    }
                });
            });

            $('#assessment_form').submit( function(e)
            {
                //e.preventDefault();
                var retvalue = true;
                $.ajaxSetup({ headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') } });
                var data = $('#multiselect_to').val();
                data = {'AssessmentCateoryIds':$('#multiselect_to').val()};

                $.ajax({
                    url: '{{route('assessment.duplicates')}}',
                    type: 'POST',
                    data: data,
                    async:false,
                    // dataType: 'JSON',
                    success: function (data) {
                        var obj = data['questions'];
                        $('#alert_placeholder').empty();
                        if(data['duplicates'] == true)
                        {
                            retvalue = false;
                            $('#alert_placeholder').append('<br>');
                            $('#alert_placeholder').append('<div class="alert alert-danger"><strong>Error:</strong> The selected categories contain duplicate questions. Check list below for details.</div>')
                            $('#alert_placeholder').append('<table class="table"><thead><tr><th>Questions</th><th>Present in categories</th></tr></thead><tbody></tbody></table>');
                            $.each(obj, function(){
                                var categories = this['categories'];
                                var categoriestxt = ''
                                $.each(categories, function(){
                                    categoriestxt = categoriestxt + this + ', ';
                                });
                                if(categoriestxt.length > 2)
                                {
                                    categoriestxt = categoriestxt.substring(0,categoriestxt.length - 2);
                                }
                                $('#alert_placeholder tbody').append('<tr><td>'+ this['title'] + ' </td> <td>'+categoriestxt+ '</td></tr>')

                            });
                        }

                    },
                    error: function(data) {
                        retvalue == true
                    }
                });

                if(retvalue == true)
                {
                    $(this).find(":button").attr('disabled', 'true');
                    $(this).find(":submit").attr('disabled', 'true');
                    $(this).find(":submit").val('Please wait..');
                    //return true;

                }
                return retvalue;
            });

        });
    </script>
@endsection

resources/views/assessments/edit.blade.php
@extends('portal-index')
@section('title', 'Edit Assessment')
@section('modalTitle', 'Edit Assessment')

@section('modalFooter')
    @if((isset($data))&& !$data->isAssessmentInUse())
        <button class="btn btn-primary pull-right" type="submit">Update</button>
    @endif
    <a href="{{route('assessments.index')}}" class="btn pull-right" data-close="Close" data-dismiss="modal">Cancel</a>
@endsection

@section('postModalUrl', route('assessments.update', $data->id))

@section('modalContent')
    <div class="row">
        <div class="col-sm-12">
            @include ('assessments.form', [
                'assessment' => $data,
            ])
        </div>
    </div>

@endsection

@section('content')
    <form method="POST" action="{{ route('assessments.update', $data->id) }}" id="assessment_form" name="edit_assessment_form" accept-charset="UTF-8" >
        {{ csrf_field() }}
        <input name="_method" type="hidden" value="PATCH">
        @yield('modalContent')
        <p>
        <div class="row">
            <div class="col-sm-12 text-right">
                @yield('modalFooter')
            </div>
        </div>
        </p>

    </form>
@endsection

@section('post-body')
    <script src="{{url('/')}}/plugins/multiselect/multiselect.min.js"></script>
    <script>
        $(function () {
            $('#multiselect').multiselect({
                submitAllLeft:false,
                sort: false,
                keepRenderingSort: false,
                search: {
                    left: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                    right: '<input type="text" name="q" class="form-control" placeholder="Search..." />',
                },
                fireSearch: function(value) {
                    return value.length > 3;
                }
            });

            $('#assessment_form').submit( function(e)
            {
                //e.preventDefault();
                var retvalue = true;
                $.ajaxSetup({ headers: { 'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content') } });
                var data = $('#multiselect_to').val();
                data = {'AssessmentCateoryIds':$('#multiselect_to').val()};

                $.ajax({
                    url: '{{route('assessment.duplicates')}}',
                    type: 'POST',
                    data: data,
                    async:false,
                    // dataType: 'JSON',
                    success: function (data) {
                        var obj = data['questions'];
                        $('#alert_placeholder').empty();
                        if(data['duplicates'] == true)
                        {
                            retvalue = false;
                            $('#alert_placeholder').append('<br>');
                            $('#alert_placeholder').append('<div class="alert alert-danger"><strong>Error:</strong> The selected categories contain duplicate questions. Check list below for details.</div>')
                            $('#alert_placeholder').append('<table class="table"><thead><tr><th>Questions</th><th>Present in categories</th></tr></thead><tbody></tbody></table>');
                            $.each(obj, function(){
                                var categories = this['categories'];
                                var categoriestxt = ''
                                $.each(categories, function(){
                                    categoriestxt = categoriestxt + this + ', ';
                                });
                                if(categoriestxt.length > 2)
                                {
                                    categoriestxt = categoriestxt.substring(0,categoriestxt.length - 2);
                                }
                                $('#alert_placeholder tbody').append('<tr><td>'+ this['title'] + ' </td> <td>'+categoriestxt+ '</td></tr>')

                            });
                        }

                    },
                    error: function(data) {
                        retvalue == true
                    }
                });

                if(retvalue == true)
                {
                    $(this).find(":button").attr('disabled', 'true');
                    $(this).find(":submit").attr('disabled', 'true');
                    $(this).find(":submit").val('Please wait..');
                    //return true;

                }
                return retvalue;
            });
        });
    </script>
@endsection

resources/views/assessments/index.blade.php
@extends('portal-index')
@section('title','Assessments')
@section('content')
    <div class="flex-wrapper">
        <div id="filter-sidebar" class="card shadow-eff1 sidebar-nav" role="navigation" style="height:170px">
            <form action="" class="">
                <ul style="margin-left:0;padding-left:0" class="list-unstyled">
                    <li>
                        <input type="hidden" name="name" class="submitable-column-name" id="submitable-column-name" value="">
                        <div class="table-search-form">
                            <input type="search" name="search-term" value="{{old('search-term', null)}}" placeholder="Search" class="search-input" data-mirror="#submitable-column-name">
                            <div class="search-option">
                                <button type="submit" data-wenk="Do the Search">
                                    <i class="fa fa-search"></i>
                                </button>
                                <a href="{{route('assessments.index')}}" role="button" data-wenk="Reset all Criteria & reload the list">
                                    <i class="fa fa-refresh"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                    <li>
                        <div class="table-search-form" style="height:50px">
                            <button type="button" class="search-column-chooser-btn">
                                <p class="search-small">Search by</p>
                                <p class="search-large">Name</p>
                            </button>
                        </div>
                        <ul class="search-column-list">
                            <li data-filter-column="name">By Name <i class="fa fa-question-circle" data-wenk="Search on First Name/Surname"></i></li>
                            <li data-filter-column="description">By Description</li>
                        </ul>
                    </li>
                </ul>
            </form>
        </div>
        <div id="table-container">
            @if(count($assessments) > 0)
            <div id="toolbar" class="shadow-eff1">
                <div class="btn-group">
                    @if($allowedActions->contains('List'))
                        <button id="sidebarCollapse" class="btn btn-default" data-toggle="offcanvas">
                            <i class="glyphicon glyphicon-align-left"></i>
                            <span>Filters</span>
                        </button>
                    @endif
                    @if($allowedActions->contains('Create'))
                        <button id="item-create" type="button" class="btn btn-sham" data-wenk="Add new" data-wenk-pos="bottom">
                            <i class="glyphicon glyphicon-plus"></i> Add New
                        </button>
                    @endif
                </div>
            </div>
            @endif
            <div class="table-responsive">
            @if(count($assessments) == 0)
                <h4 class="text-center">Its a bit empty here. You may click <a href="javascript:;" class="text-primary item-create">here</a> to add a new assessment</h4>
            @elseif($allowedActions->contains('List'))
                <table id="new-table" data-toggle="table">
                    <thead>
                        <tr>
                            <th data-sortable="true">Name</th>
                            <th data-sortable="true">Description</th>
                            <th data-sortable="true">Passmark Percentage</th>

                            <th data-sortable="false" data-tableexport-display="none">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($assessments as $assessment)
                        <tr id="tr{{$assessment->id}}">
                            <td>{{ $assessment->name }}</td>
                            <td>{{ $assessment->description }}</td>
                            <td>{{ $assessment->passmark_percentage }}</td>

                            <td data-html2canvas-ignore="true">
                                <div class="btn-group btn-group-xs" role="group">
                                    @if($allowedActions->contains('Write'))
                                        <a href="#modal-text" data-wenk="Edit" class="b-n b-n-r bg-transparent item-edit" onclick="editFullPage('{{$assessment->id}}', event)">
                                            <i class="glyphicon glyphicon-edit text-primary"></i>
                                            </a>
                                    @endif
                                        <a href="#light-modal" data-wenk="Clone" class="b-n b-n-r bg-transparent item-clone" onclick="editCloneAssessment('{{$assessment->id}}', event)">
                                            <i class="fas fa fa-clone text-primary" style="-webkit-text-stroke-width:1px;"></i>
                                        </a>
                                        <a href="#light-modal" data-wenk="Preview" class="b-n b-n-r bg-transparent item-preview" onclick="previewAssessment('{{$assessment->id}}', event)">
                                            <i class="glyphicon glyphicon-blackboard text-primary"></i>
                                        </a>
                                    @if($allowedActions->contains('Delete'))
                                            <a href="#!" class="b-n b-n-r bg-transparent item-remove" data-wenk="Remove" onclick="deleteForm('{{$assessment->id}}')">
                                                <i class="glyphicon glyphicon-remove text-danger"></i>
                                            </a>
                                    @endif
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                <nav>
                    {!! $assessments->render() !!}
                </nav>
            @endif
            </div>
            @component('partials.index', ['routeName'=> 'assessments.destroy'])
            @endcomponent
        </div>
    </div>
@endsection

resources/views/assessments/preview_form.blade.php
<div class="row">
    <div id="assessmentPreview">
        <div id="form">
            {!!  (isset($html)?$html:"") !!}
        </div>
    </div>
</div>